### ISSUE TITLE
Vectorization of water monomer energy [WIP]

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#12]
Now the reference water monomer energy calculation is implemented, we will proceed to vectorize this calculation.

@dgasmith , will we use autovectorization from intel compilers, or we set everything manually?

**Comment by dgasmith** [comment]
Most compliers have "autovectorization" when compiled with higher levels of optimization. I don't know what you mean by setting everything manually (perhaps OMP SIMD flags?). You could use ICC for its nice vector reporting, but I would not necessarily use intel specific pragma's.

**Comment by chemphys** [comment]
I tried to compile the basic example 2.3.2 in 
https://www.kernel.org/pub/linux/kernel/people/geoff/cell/ps3-linux-docs/CellProgrammingTutorial/BasicsOfSIMDProgramming.html
But doesn't seem to compile, since it does not identify some of the flags:
gcc: error: unrecognized argument in option ‘-mabi=altivec’
gcc: note: valid arguments to ‘-mabi=’ are: ms sysv
gcc: error: unrecognized command line option ‘-maltivec’

So I went ahead and tried autovectorization with simple examples. I tried to do it with g++ and icpc, to see the optimization reports of both of them, aligning and not aligning the data. I followed the documentation in
https://software.intel.com/en-us/articles/data-alignment-to-assist-vectorization for icpc, and in
https://gcc.gnu.org/onlinedocs/gcc/Developer-Options.html for g++
And my examples are in a repo in 
https://github.com/chemphys/vectorization/tree/master/src/my_tests

Regarding this I have a couple questions/comments:
- I guess that what I coded there will be similar to what we are going to do in the code, right? We will get all the coordinates of the similar monomers (in this case we only have water, but at some point this century we will have something else), align them, and send them to the function that gets the energy, adding the keyword "assume_aligned" and perform the operations in loops. Is that right?
- How big should we make the width of the alignment? I think you mention 512 (8 doubles), but is there any way to define that width automatically, according to the machine the user is using? Does it matter right now?

While I wait for your reply, I will see how I can make Travis to properly work. Thanks for the initial scripts. I am also waiting for the admin to upgrade cmake to version 3.3, since the one he installed last week is 2.8 (thats why in my cmake I had the 2.8 minimum version required).

**Comment by dgasmith** [comment]
It probably does not make sense to work with intrinsics for this project. You would have to build a generator to produce fairly complex code. Fortunately, your program is trivially vectorizable and most compilers will take care of it, it is more about organizing the data in such a way that it is amenable to vectorization.

It is best to try the simplest thing first and check the vector report to see whats going on. There is no need to worry about alignment beyond ensuring that the data is contiguous for now.

**Comment by chemphys** [comment]
Hey @dgasmith , I have a probably stupid question, but might be worth to ask.
I am rewritting the pot_nasa function 
 https://github.com/paesanilab/clusters_ultimate/blob/master/src/potential/1b/ps.cpp#L491](url) and I am doing the following:
- I am adding a third argument (size_t nw) which will indicate the number of water molecules we have
- I am looping overall the water molecules every time that the code does the same for every water molecule, so the compiler can identify this a same instruction for different data.
Let me know if this is not correct. Assuming it is, my question is the following:
The different variables that the code creates and use are declared as double[]. You mention that anytime I can I should use vector<double> instead of raw pointers. With the vectors, I know I can use the reserve() function to reserve the memory, and then I need to push_back the vector elements (0.0) to initialize them. For what I have read, I think I cannot assign a value directly, right? Let's say:
```
std::vector<double> a;
a.reserve(10);
a[2] = 2.43;
```
is going to fail, right?
Is it worth to use vectors or is better to use double * a = new double[10], and delete memory at the end? If we want it aligned, we will need to declare the aligned vector anyway, so sincerely I don't think it matters right now. What is your opinion?

**Comment by dgasmith** [comment]
The code you wrote is perfectly valid. The main note here is that simply calling `reserve` does not initialize those values unlike `resize` which will use the default constructor for each value.

You should be careful, `double vector[3]` and `double* vector = new double[3]` do two very different things (heap vs stack). My main point about using `std::vector` was that for long term holding and passing data it is probably wiser to use, for anything temporary (say purely inside a function) it doesn't matter much. At the same time using `std::vector` doesn't hurt you that much besides the memory alignment issue.

Again, I would recommend doing the simplest thing first. My original comments were mainly focused on changing the data layout a bit so that the compiler has a chance and will make it easier down the road if you care to do high levels of optimization within this function. To really get this part perfect would take a lot of time considering the complexity and I would not recommend doing that at the moment.

Please take a look into [Loopy](https://documen.tician.de/loopy/) to give you an idea of what it would take to really get this right.

**Comment by chemphys** [comment]
Hey @dgasmith , I think I made the code vectorizable. I attach the vectorization report from icpc. The loops that it doesnt vectorize are loops that icpc consider inneficient to do so. I will go on and start implementing 2b and 3b, and start vectorization of those files, if you think that 1b is OK.

Thanks!
[ps.optrpt.txt](https://github.com/paesanilab/clusters_ultimate/files/1297294/ps.optrpt.txt)

**Comment by dgasmith** [comment]
Did you time it with and without optimization and do you have any idea of what the optimal speedup is? Also, do you agree with Intel's vector report?

**Comment by chemphys** [comment]
I don't really understand why it doesn't vectorize (as example) loop in line 521 or 529, since in principle are additions or multiplications. Is that because I am using the +1 in the pointer? Or anytime I use + i?
And regarding the timings I haven't done it yet. I am adding right now the chronos library so I can get ms accuracy.

**Comment by chemphys** [comment]
Wait, i think i see what is wrong.
Let me see if i can fix that.
________________________________

**Comment by chemphys** [comment]
Yeah, fixed. Now I am having a segfault with intel compilers that I don't have with g++... I will work on that.
