### ISSUE TITLE
Vectorization of polynomials for H2O 2b/3b [WIP]

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#17]
Hey @dgasmith , I started thinking how to vectorize the polynomial files.
As you know, most of the part of those files is declaring constants that depend on other constants:
```
   ...
    const double t5627 = t1948*t73;
    const double t5628 = t1961*t77;
    const double t5629 = t1963*t126;
    const double t5630 = t1961*t132;
    const double t5631 = t1963*t136;
    ...
```
If we want to put several systems and make a loop, the "straight forward" idea is to make those variables an array, not constant, and leave in the form of:
```
   ...
    t5627[n] = t1948[n]*t73[n];
    t5628[n] = t1961[n]*t77[n];
    t5629[n] = t1963[n]*t126[n];
    t5630[n] = t1961[n]*t132[n];
    t5631[n] = t1963[n]*t136[n];
    ...
```
The problem I see with this is that there might be then thousands of arrays. What do you think?

**Comment by chemphys** [comment]
Hey @dgasmith , 
I got 2 and 3 body to work, and 2b is in the vectorized format. However, if I just use the standart optimizations, I get this message for both the polynomila functions with and without gradients:
```
LOOP BEGIN at /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(11,3)
   remark #15533: loop was not vectorized: loop exceeds complexity limits. Consider overriding limits (-override-limits) or using simd directive.
LOOP END
```
I looked for this remark in the intel website, and this means that the loop is too big to be safely vectorized. Then I use the keyword -qoverride-limits, and I get:
```
LOOP BEGIN at /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(11,3)
   remark #25460: No loop optimizations reported
LOOP END
```
for the non-gradient polynomial function, in which after googleing it, it simply understands that it cannot be optimized.
And then I get:
```
LOOP BEGIN at /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(11,3)
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(6584,5) ]
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(6589,5) ]
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(6588,5) ]
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(6587,5) ]
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(6586,5) ]
... ... ...
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(11236,5) ]
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(11240,5) ]
   remark #25084: Preprocess Loopnests: Moving Out Store    [ /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x.cpp(11239,5) ]
LOOP END
```
 For the function with gradients. For what I understood in the few places that explain what is this `Preprocess Loopnests: Moving Out Store ` , it just takes out of the vectorizable loop what it doesn't need to be vectorized. Still, is odd since is only after line 6584, which is the term t6000. Before that, no complains. Does it mean that this loop is too large? Would splitting the file help?

**Comment by dgasmith** [comment]
It is a complex function, but there isn't a immediate reason (to me) why the compiler cannot do this. Increasing the override limits is usually not a good idea; however, the other compiler suggestion of trying a `pragma amp simd` is a really good one.

Please upload the full vector report of the result to a gist if it does not work.

**Comment by chemphys** [comment]
Will this `pragma omd simd` work on g++? Or I will have to change it?

**Comment by dgasmith** [comment]
It will work on `g++`, but you will have to incorporate OMP flags into your build (one of the reasons we moved to CMake). See [here](https://stackoverflow.com/questions/12399422/how-to-set-linker-flags-for-openmp-in-cmakes-try-compile-function) and [here](https://cmake.org/cmake/help/v3.0/module/FindOpenMP.html). You should then wrap your OMP code in `ifdef`'s:

```
#ifdef _OPENMP
   #include <omp.h>
#else
```

**Comment by chemphys** [comment]
Perfect. I'll look at this.
Thanks!

**Comment by chemphys** [comment]
@dgasmith , when you said `pragma omd simd`, did you mean `pragma omp simd`?

**Comment by dgasmith** [comment]
Apologies, looks like autocorrect got to me. 

-Daniel Smith

**Comment by chemphys** [comment]
In any case, that doesn't help either (with intel compilers). I attach the full optimization report here for the shortest of the polynomials (the 2b, no gradient).
It still complains that the loop is too large. And also, while compiling, this appears in the output:
```
[ 33%] Building CXX object potential/2b/CMakeFiles/2b.dir/poly-2b-v6x-nogrd.o
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(9): (col. 1) remark: Some OpenMP processing was skipped to constrain compile time. Consider overriding limits (-qoverride-limits).
/home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(9): (col. 1) remark: Some OpenMP processing was skipped to constrain compile time. Consider overriding limits (-qoverride-limits).
Space exceeded in Data Dependence Test in _ZN3x2o11poly_2b_v6x4evalEmPKdS2_
Subdivide routine into smaller ones to avoid optimization loss
/home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(11): (col. 1) warning #13379:  was not vectorized with "simd"
```
Any thoughts? A part from breaking the function, I am out of ideas.

[poly-2b-v6x-nogrd.optrpt.log](https://github.com/paesanilab/clusters_ultimate/files/1335262/poly-2b-v6x-nogrd.optrpt.log)

**Comment by bennybp** [comment]
Intel has two more vectorization pragmas you can try. In particular, `#pragma vector` has an `always` option which may override some checks. No guarantees though - that function might just be too long/complex for automatic vectorization, unfortunately.

Details on `#pragma vector`: https://software.intel.com/en-us/node/524559

This other is `#pragma simd`, which I'm not as familiar with.

**Comment by chemphys** [comment]
Thanks! I will try this. Unfortunately today i am out of the office moving thousands of boxes to my new place.. i will give it a try!

Thanks a lot for your tips!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by agoetz** [comment]
The compiler needs to allocate storage to keep track of variables during optimization, e.g. to check if there are loop dependencies. This message "Space exceeded in Data Dependence Test in [...]" basically says that the compiler ran out of memory. I don't know if there is a way to get around this or if there are other limitations to vectorization. Does any of you have contacts to Intel compiler engineers? Otherwise I could reach out to my contacts at Intel.

**Comment by chemphys** [comment]
OK, @bennybp . With the `#pragma vector` keyword it says that is possible to vectorize, but it seems innefficient. Then I follow the suggestion from the compiler, adding `-vec-threshold0`, but apparently the compiler totally ignores it:
```
/home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(9): (col. 1) remark: Some OpenMP processing was skipped to constrain compile time. Consider overriding limits (-qoverride-limits).
Space exceeded in Data Dependence Test in _ZN3x2o11poly_2b_v6x4evalEmPKdS2_
Subdivide routine into smaller ones to avoid optimization loss
/home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(12): remark #15335:  was not vectorized: vectorization possible but seems inefficient. Use vector always directive or -vec-threshold0 to override
```
I also tried with the `pragma vector always`, but it also ignores it (same message is repeated).

**Comment by chemphys** [comment]
@agoetz I do not have any contact in intel.

**Comment by dgasmith** [comment]
@jeffhammond We are trying to get the intel compiler to vectorize the [this expression](https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x-nogrd.cpp) which is atomically generated from some CAS. This expression is admittedly a bit lengthy, but should be vectorizable automatically. Any ideas here without going to intrinsics?

**Comment by jeffhammond** [comment]
Autovectorization works a lot better if you have tight loops, rather than thousands of scalar statements.  Can you generate loops rather than unrolling everything inside of the `nv` loop?

I gave the same advice to Ed Valeev years ago w.r.t. LIBINT, by the way.

**Comment by jeffhammond** [comment]
Adding any SIMD directive on the `nv` probably won't help, because the body almost certainly requires many more registers than exist, so generating SIMD instructions won't help, because you'll just thrash L1.

Anyways, I assume the source is the output of a code generator.  You can't have your cake and eat it too: either your code generator needs to generate vector intrinsics or you should generate a compact mathematical expression that compilers are accustomed to consuming.

This is certainly not the first project to run into the cake have-eat dichotomy.  Many years ago,
 [FEniCS](https://fenicsproject.org/) found they could only compile with `-O0` because their code generator output was so large it could not be optimized with GCC.

**Comment by chemphys** [comment]
Hey Jeff, thanks for your reply. The function you have been looking at is the output of a MAPLE optimization to evaluate a polynomial function. This polynomial has as many terms of different degrees (usually not more than 6th order) as the pointer `double a[N]`. Passing this polynomial as input, MAPLE optimizes the evaluation to do the less number of operations possible. 

The function [here] (https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x-nogrd.cpp) takes 3 arguments:
- `size_t nd` is the number of data sets that need to be evaluated
- `double * a` is a set of constants (always the same for any individual data set)
- `double * x` is an array that contains all the data of all the sets.

In order to make loops inside, it would require to have a vector or double pointer `t` rather than a bunch of `const double tXXX`. However, if now we have in this function around 15K t constants, this means that we would have to store an array of 15K * nd, where nd can be easily more than 10K for a relatively small system. And this is the smallest function we will deal with, since the function that also computes gradients (see [here] (https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x.cpp) is even more complicated and with more terms. 

@dgasmith , at the first meetings you already mentioned that maybe it would be necessary to use the non optimized code for the polinomials in order to be able to vectorize it. The code generates the evaluation without gradients in a direct way, so if we want to do that, I will also need to have a way to obtain these gradients in a direct way.

**Comment by dgasmith** [comment]
@jeffhammond Thanks for the tip, I was hoping autovectorization would be smart enough to discard unused temporaries to keep in registers as most of the temporaries can be destroyed shortly after creation. I guess I will wait a bit longer until compilers are no longer based in reality.

@chemphys If we did hold a 15k * 10k matrix per thread this actually isn't too bad (~1GB), plus you can always chop it up further. However, if we actually built this large temporary we would require paging DRAM which would be very slow due to the latency (this probably goes back to my comment that raw FLOP counts do not always win). Due to the sheer number of temporaries, even building tiny vectors the width of your SIMD unit will push the data out of registers into L1. What would have to happen is specifically creating a temporary that can live in registers until it used and then promptly destroyed. Looking at the code and how the temporaries are used this is likely the case, but unknown until it is actually done.

My recommendation is to just skip vectorizing this, I still suspect your induction and dispersion terms will completely swamp out any inefficiencies of these local terms. I was hoping that we could get vectorization practice in a long the way, but not if we have to swap to our own code generator.

**Comment by jeffhammond** [comment]
Unless MAPLE reduces the number of operations by more than a factor of 4, you would be better off using naive math that vectorizes, than using an optimized math expression that uses scalar instructions.  And that 4 is for AVX2 with 64-bit floats.  It turns into 8 with AVX-512 or 32-bit floats and 16 with both.

Where can I find the reference implementation of this code in terms of `exp()` etc.?

**Comment by jeffhammond** [comment]
@dgasmith In theory, compilers can do this, but pretend you are a compiler developer: do you prioritize optimizing the output of code generators or humans?  Who is writing more code these days?  Who is more likely to need (and be willing to pay for, if it's a commercial product) help from the compiler?

Maybe I am being pessimistic.  You can set the "override all limits" option and see what happens, as noted in one of the optimization reports shown above.

**Comment by dgasmith** [comment]
@jeffhammond It was more of a hope than anything else, the market force are quite apparent. If anything I would expect the code generators to start paying more attention to this. [loo.py](https://documen.tician.de/loopy/) is a great example.

**Comment by chemphys** [comment]
The evaluation is divided in two parts. The structure [x2b_v9x](https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/x2b-v9x.h) receives a set of XYZ coordinates. Then it calculates all the distances that play a role in the polynomials, and it calculates the exponential values. Those values are passed to the polynomial function [with](https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x.cpp) and [without](https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x-nogrd.cpp) gradients. Then it returns the energy to the structure and the gradients if you use the gradient function.

In order to show you exactly the original function from where the polynomial function [with](https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x.cpp) and [without](https://github.com/chemphys/clusters_ultimate/blob/master/src/potential/2b/poly-2b-v6x-nogrd.cpp) gradients come from, I need to look in the archive data of our lab. But they will have this structure:
```
double poly_model::eval_direct(const double a[597], const double x[15])
{
    double p[597];
    p[0] = x[11] + x[14] + x[13] + x[10];
    p[1] = x[9] + x[12] + x[7] + x[8];
    p[2] = x[6];

    p[3] = x[10]*x[5] + x[11]*x[2] + x[14]*x[2] + x[10]*x[2] + x[13]*x[2] + x[13]*x[5] + x[14]*x[5] + x[11]*x[5];
    p[4] = x[6]*x[9] + x[6]*x[7] + x[12]*x[6] + x[6]*x[8];
    p[5] = x[4]*x[9] + x[1]*x[8] + x[0]*x[7] + x[3]*x[9] + x[12]*x[4] + x[0]*x[8] + x[1]*x[7] + x[12]*x[3];
    p[6] = x[14]*x[3] + x[11]*x[1] + x[11]*x[3] + x[10]*x[1] + x[0]*x[14] + x[10]*x[4] + x[0]*x[13] + x[13]*x[4];
    p[7] = x[5]*x[6] + x[2]*x[6];
    p[8] = x[12]*x[8] + x[7]*x[9] + x[8]*x[9] + x[12]*x[7];
    p[9] = x[14]*x[6] + x[11]*x[6] + x[10]*x[6] + x[13]*x[6];
    ...
    p[589] = x[5]*x[6]*x[6]*x[6] + x[2]*x[6]*x[6]*x[6];
    p[590] = x[2]*x[2]*x[7]*x[8] + x[12]*x[5]*x[5]*x[9];
    p[591] = x[3]*x[5]*x[7]*x[7] + x[4]*x[5]*x[8]*x[8] + x[12]*x[12]*x[1]*x[2] + x[0]*x[2]*x[9]*x[9];
    p[592] = x[0]*x[0]*x[12]*x[2] + x[1]*x[1]*x[2]*x[9] + x[3]*x[3]*x[5]*x[8] + x[4]*x[4]*x[5]*x[7];
    p[593] = x[10]*x[11]*x[1]*x[6] + x[11]*x[14]*x[3]*x[6] + x[10]*x[13]*x[4]*x[6] + x[0]*x[13]*x[14]*x[6];
    p[594] = x[10]*x[11]*x[13]*x[14];
    p[595] = x[0]*x[1]*x[6]*x[6] + x[3]*x[4]*x[6]*x[6];
    p[596] = x[6]*x[6]*x[6]*x[6];

    double energy(0);
    for(int i = 0; i < 597; ++i)
        energy += p[i]*a[i];

    return energy;

}
```
Here, `double * a` and `double * x` are the same as in the other two files. For the system we are dealing with, `double * a` will have a length of 1153 instead of 597 as in the example I pasted.

And also, I just tried with override-limits and it makes no difference. Still says the same when compiling:
```
[ 33%] Building CXX object potential/2b/CMakeFiles/2b.dir/poly-2b-v6x-nogrd.o
icpc: remark #10397: optimization reports are generated in *.optrpt files in the output location
/home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(12): remark #15335:  was not vectorized: vectorization possible but seems inefficient. Use vector always directive or -vec-threshold0 to override
```
And nothing in the report:
```
LOOP BEGIN at /home/mrierari/codes/clusters_ultimate/src/potential/2b/poly-2b-v6x-nogrd.cpp(12,3)
   remark #25460: No loop optimizations reported
LOOP END
```

**Comment by chemphys** [comment]
@dgasmith , then we can move to dispersion and electrostatics. I will leave the 2b and 3b as it is right now (with the loop, knowing that it wont be vectorized) and focus on implementing the dispersion and electrostatic routines. 
Thanks @jeffhammond , @bennybp, @dgasmith and @agoetz for all your help!

**Comment by chemphys** [comment]
Closing this issue for now. It may be revisited later on.
