### ISSUE TITLE
Dispersion Interaction [WIP]

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#19]
I will proceed to add the dispersion interactions to the code. 

In classical forcefields, the dispersion interaction (and non bonded interactions in general) depends on the type of atom, and each pair of atom types has a defined set of parameters to be used in the non-bonded contribution. However, in our approach, each pair of monomers has defined C6 coefficients. This means that water with water will have a defined C6 for O-O, O-H and H-H, CO2 with water will have defined coefficients for C-OW, C-HW, O-OW, O-HW, and so on.

Also, some large monomers, with atom distances of 4 bonds (distance 1-5) such as N2O5 will also have intramolecular dispersion that needs to be taken into account.

The way that I think might be the best to implement this is the following:
1. Create a general function that given C6 and damping (d6), C8 and damping (d8), and coordinates of two atoms, returns the dispersion contribution of that pair.For now we only use the C6/d6, but it will be nice if at least you also have the option of add the C8 contribution just in case.
2. Create a function that returns a vector of C6 and d6 for a given dimer, and since all the atom pairs have to be evaluated, no need to return the atom pairs. However, this will imply that the order of the atoms of the molecule is in a preset order. For now, the user has to add it to the input directly, but later on we can try to make the code reorder it if it is necessary.
3. Create a function that returns the same information but for a single monomer. Here there is a need to find a way to store the excluded pairs and non-excluded pairs for a given monomer. This will also be useful for the electrostatics. I think it has to be done during the monomer set up.
4. Create a dunction that evaluates the dispersion for a chunk of monomers/dimers to allow vectorization.

@dgasmith , I have a couple questions:
1. Does this way seem reasonable?
2. To store the excluded pairs, is a vector of vectors a bad idea? Would it be better to create a structure rather than vector of vectors?

Thanks!

**Comment by dgasmith** [comment]
A `std::vector<std::vector<...>>` is fine, just realize that the memory is not continuous in the outer `std::vector`.

If you compute the C6/C8/d6/d8 of a given dimer your might as well sum the data and simply return the energy unless you require this data elsewhere. It would be better with your K-DTree implementation to give the host atom along with *all* of its neighbors and return the summed dispersion energy.

One would assume that the order of your atoms in your System is immutable. The domain decomposition may create domains of different orders, but your still referencing atoms/monomers in these domains relative to the primary System object.

**Comment by chemphys** [comment]
For the vector of vectors is fine. This is just to keep it stored during the full simulation, since the dispersion has to be calculated at each step. The inner vector contains all the data for each pair, and the outer vector is the vector that contains the different vectors for all the different dimers.

With the kd-tree, I don't see if I understand the point. Since we know the monomers that will be inside the cutoff, we can just loop over the atoms of those pairs of monomers (we have the dimer vector). Do you think it would be better to run a kd-tree with all atoms (instead of monomers as it is now) and find and identify all pairs from there? I think it will extremely complicate the evaluation, since we don't have atom identities but atoms that belong to a given monomer.

Thanks!
