### ISSUE TITLE
Timings Info

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#21]
Hey @dgasmith ,

I made a few modifications to the code:
- AddClusters has been modified to only take into account the first N monomers for **i** in **<i,j>** pairs, and **<i,j,k>** trimers. These doesn't speed down the code and allows to deal with as many molecules as we want. N, for now, is fixed in the initialization of the system to 4096, which is the maximum number I saw that was not affecting the speed. If N = 8192, the speed starts decreasing.
- I added maxNDimEval_ and maxNDimEval_ variables in the system. This is the maximum number of dimers/trimers that will be evaluated at once. For now is set to 1024 in the initialization.
- The monomer energy calculation had problems for systems larger than 8192 water molecules, so I also added maxNMonEval_ and set it to 1024. The reason is that water is the only monomer that will have an "special" energy function, since all the other monomers will be evaluated through polynomials. I keep 1024 for consistency with dimers and trimers.

These modifications seem to have a very positive effect on the timings. I have tested up to 64K molecules, and the timing seems to increase linearly with N for 1B, 2B and 3B. I will collect some data and make some figures to show the timings for each component as a function of size.
The largest system I plan to try for now is 133K water molecules, which I think is a nice goal for now. 

All these changes are in a local branch in my machine, that I will merge with the master and push it to the pull request if you think that's OK. 

Just a note, all these results are obtain in my local machine, compiled with intel with optimizations. Without optimizations everything is slowed down about an order of magnitude. I am excited to see if we can make the electrostatics as fast as the 3B (for now, the bottleneck by an order of magnitude).

I will keep you posted. See you!

**Comment by dgasmith** [comment]
Sounds great, let me know when you have a few figures to show off.

**Comment by chemphys** [comment]
Yeah, is something we can explore.

Regarding the timings, I post here a few plots.
There first three plots are comparisons between our old C++ energy code (the one that I have been using for REMD, and all the different analysis, labeled in the plots as **Clusters**) and the new one we are writting (labeled as **Ultimate**). The timings are in miliseconds, and each plot corresponds to one-body, two-body and three-body energy of the full system, indicated in the title of the plot.

![1b](https://user-images.githubusercontent.com/10054173/31321511-257eef04-ac3c-11e7-85e0-2e3784601d2b.jpg)
![2b](https://user-images.githubusercontent.com/10054173/31321535-90906f7a-ac3c-11e7-8a8f-d8eb99a9b061.jpg)
![3b](https://user-images.githubusercontent.com/10054173/31321536-94a44348-ac3c-11e7-8fb0-0d4f8cca014f.jpg)

Then I also have a few comparisons between the new version of the software and the previous one. The new version has all the modifications you mentioned: not getting the dimers/trimers all at once, and do batches of calculations. The 1B is also done in batches of 1024 monomers. Here, the old version is labeled as CU_noBatch and the new one as CU_batch. Note that there are no numbers for systems larger than 2048 since the noBatch code was no running out of memory.

![1b](https://user-images.githubusercontent.com/10054173/31321567-f32a49da-ac3c-11e7-82c9-c006ae179c94.jpg)
![2b](https://user-images.githubusercontent.com/10054173/31321568-f53c7216-ac3c-11e7-895a-4e5503f828e9.jpg)
![3b](https://user-images.githubusercontent.com/10054173/31321570-f7c2a186-ac3c-11e7-9b76-fb7bad9727e7.jpg)

**Comment by agoetz** [comment]
@chemphys This looks great. If you plot your timings on a log-log scale, it will be easier to see what is going at all problem sizes.

**Comment by chemphys** [comment]
I leave them here:
![1b](https://user-images.githubusercontent.com/10054173/31352294-169a3528-ace3-11e7-848c-439ce59dae26.jpg)
![2b](https://user-images.githubusercontent.com/10054173/31352295-18670b10-ace3-11e7-8839-eed51611074e.jpg)
![3b](https://user-images.githubusercontent.com/10054173/31352298-1b00749c-ace3-11e7-9d1c-bf2161072884.jpg)
