### ISSUE TITLE
Tang-Toennies function modification [WIP]

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#22]
The Tang-Toennies damping function needs to be modified. Not a priority, but will be done.

**Comment by chemphys** [comment]
Hey @fpaesani ,
I have been looking to the Tang-Toennies damping function coded in the reference C++ code. Daniel noticed that there was a weird loop, and I cannot see why is that loop there. The actual function is as follows:
```
  double tang_toennies(int n, const double& x) {

    assert(n >= 0);
    int nn = n;
    double sum = 1.0 + x/nn;

    while (--nn != 0)
        sum = 1.0 + sum*x/nn;

    double tt = 1.0 - sum*std::exp(-x);

    if (std::fabs(tt) < 1.0e-8) {

      double term(1);
      for (nn = n; nn != 0; --nn)
        term *= x/nn;

      sum = 0.0;
      for (nn = n + 1; nn < 1000; ++nn) {
        term *= x/nn;
        sum += term;

        if (std::fabs(term/sum) < 1.0e-8)
          break;
      }

      tt = sum*std::exp(-x);
    }

    return tt;
  }
```
The first part,
```
    assert(n >= 0);
    int nn = n;
    double sum = 1.0 + x/nn;

    while (--nn != 0)
        sum = 1.0 + sum*x/nn;

    double tt = 1.0 - sum*std::exp(-x);
``` 
is the one that calculates the damping. The second part 
```
    if (std::fabs(tt) < 1.0e-8) {

      double term(1);
      for (nn = n; nn != 0; --nn)
        term *= x/nn;

      sum = 0.0;
      for (nn = n + 1; nn < 1000; ++nn) {
        term *= x/nn;
        sum += term;

        if (std::fabs(term/sum) < 1.0e-8)
          break;
      }

      tt = sum*std::exp(-x);
    }
```
is only activated if the damping result is smaller than 1E-08. Do you have any idea why it was coded like this? I have not been able to locate anywhere this part of the algorithm. @agoetz , any idea?

**Comment by fpaesani** [comment]
I believe it is just for stability reasons. I think we can trust Volodymyr's code.

**Comment by chemphys** [comment]
Yeah, I do trust it. The only proble is that this loop, since it has multiple exits, prevents automatic vectorization of the dispersion forces calculation. I just wanted to rewrite it in a way that it doesn't do that. I will think about it later, then, because this is not critical. Thanks!

**Comment by chemphys** [comment]
Since dispersion takes nothing in comparison with the rest of the code, we will leave this closed.
