### ISSUE TITLE
Header clean up to reduce compilation time

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#34]
Hey @dgasmith ,

As we have discussed, we have a problem with the compilation time of the package using g++. In our local machines and the supercomputers, this is not really a problem, since although it takes a little bit to compile, it ends compiling. However, in travis it takes too long. The two options you suggested are:
1. **Try to reduce the number of header files**. Sincerely, I didn't fully understand what do you mean with that, and I would really appreciate if you can have a look at this possible solution.
2. **Convert the polynomial files to C**. If option 1 doesn't help, I can rewrite the polynomial files to be C-like, and then compile them with gcc. However, I will need help to hook this in CMake, since I don't really know how to tell cmake to compile some files with gcc and some with g++ (unless it detects it automatically through the extension).

If you can have a look at Option 1 one of these days, I would really apreciate it. All the polynomial files are in the [potential](https://github.com/paesanilab/clusters_ultimate/tree/master/src/potential) folder, under the folder name of [1b](https://github.com/paesanilab/clusters_ultimate/tree/master/src/potential/1b), [2b](https://github.com/paesanilab/clusters_ultimate/tree/master/src/potential/2b), and [3b](https://github.com/paesanilab/clusters_ultimate/tree/master/src/potential/3b). The polynomial files start always with _poly-..._ All the polynomial files are used by the x1b-... x2b-... files, which contain the object that has the energy evaluation function. 
Thanks!

**Comment by dgasmith** [comment]
For 1) it doesn't look like you have the issue. Occasionally folks get into a bit of a bind where they make "convenience headers" which have many extraneous includes. This make what looks like a small import really include far too much and can greatly increase your compile time.

For 2) we might need to bring in @bennybp for the hybrid compilation.

One other option is to give custom flags to the 3-body potential, [example](https://github.com/psi4/psi4/blob/master/psi4/src/psi4/detci/CMakeLists.txt#L3). Where you explicitly turn off all optimization for these files. From looking at them and other issues, there is little that the compiler can do anyways and are currently a small fraction of your total time.

**Comment by chemphys** [comment]
Using the flags worked. Compilation time in travis reduced to 5 min with g++!!
Closing issue.
