### ISSUE TITLE
2B and 3B parallelization

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#37]
I started the parallelization of 2B and 3B. I will put here scaling tests of the different parts, and the global scaling.

**Comment by chemphys** [comment]
@dgasmith , I prefered to open a new issue with just these 2b/3B parallelization.
There was a small bug in the indexing and I had to find it and fix it. Now everything seems to work fine.
I would appreciate if you can also put here the "few minor syntactic comments and one performance comment" even if they won't matter a lot. I prefer to have things as OK as possible!

Thanks!

**Comment by dgasmith** [comment]
I believe I made three comments on the code base, did you get them?

**Comment by chemphys** [comment]
I missed that!
"You might need to add separate grad buffers to write into. These blocking operations could potentially be expensive and then implement a binary tree summation. Just as a general preference it might be nice to abbreviate gradient as grad to be a bit clearer."
I got it now. I will update the names and see if I can implement this binary tree.

**Comment by chemphys** [comment]
I am going to close this issue, and open one to implement the binary tree in the 2B and 3B gradient blocking. I will work on this after I write tests for everything, if you agree.

**Comment by dgasmith** [comment]
Sounds good. As a note a binary tree sum is very simple. If you have N buckets you can use N/2 threads to sum pairs of buckets and then use N/4 threads to sum the next pairs of buckets and so on down the tree until you have a single array left. The other option is to use different thread to sum over different sections of the gradient rows which is simpler and likely more efficient in this case.

**Comment by chemphys** [comment]
Cool, will do that then.
Thanks!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chemphys** [comment]
Hey @dgasmith ,
I will put here the speedup plots for the different functions. I think there is room for improvement.
Note that the time and speedup is for the entire function itself. This is, for the 2b, the time that I have measured is for the entire 2-body energy calculation (see time stamps in the [system.cpp](https://github.com/chemphys/clusters_ultimate/blob/mrr/parallelization/src/bblock/system.cpp#L156) file, at the energy function.

I did the test for several sizes of water systems, labeled as 16 H2O, 32 H2O... What do you think we should do? Should we try to improve this a little bit before continuing with deep testing? Or is better to move on, make the tests and try to implement this in an MD package before trying to improve this?

Thanks!

![2b](https://user-images.githubusercontent.com/10054173/36232652-83109738-1197-11e8-89ef-fe30c48812ca.jpg)


![3b](https://user-images.githubusercontent.com/10054173/36232655-852daccc-1197-11e8-92a3-0f70ba0e7ccc.jpg)


![electrostatics](https://user-images.githubusercontent.com/10054173/36232662-8b285f6e-1197-11e8-96de-211b11bcb0a0.jpg)


![totalenergy](https://user-images.githubusercontent.com/10054173/36232669-8e692730-1197-11e8-9f01-a37d0b6ac2c8.jpg)

**Comment by dgasmith** [comment]
I thought the electrostatics was threading with very high efficiency in previous charts?

I wasn’t expecting stellar improvements without some work so this isn't entirely unexpected. At this point it’s best to run the 2-body through vtune to see what’s going on. Kind of feels like some sort of blocking operation is killing you. 

-Daniel Smith

**Comment by agoetz** [comment]
@chemphys What algorithm are you using to converge the induced dipoles? @zonca is threading the OpenMM CPU platform and was not able to get a good speedup for induced dipoles. There is a new implementation in OpenMM that uses DIIS convergence acceleration, which seems to be quite efficient, Andrea will port this over to the MB-pol electrostatics in OpenMM. Maybe you two should also talk.

@chemphys If you are familiar with VTune, it would be good if you could sit down with @yazhai who is also working on performance optimizations, and it may be useful to use VTune. Thanks!

**Comment by chemphys** [comment]
@agoetz , I can stop by tomorrow during the morning, when there is no visitation stuff to do.
I am not an expert on VTune, but I know how to get the things. @yazhai , will you be around?

**Comment by chemphys** [comment]
Hey @dgasmith , I did a couple of modifications in the 2B and 3B functions, and now the speed up looks slightly better. I put the new ones below. As a note, my local machine has two sockets of 6 cores each. The weird 16 water molecules behavior is due to the short time that it takes to get the 2B (< 10ms), and since the times are in integer ms, the oscillations are pretty visible there.

I will investigate how can I improve the performance of the small clusters for 2B and 3B, and then I will go for electrostatics.

![2b](https://user-images.githubusercontent.com/10054173/36289799-d9fd2950-1276-11e8-88ad-dbc26a5f92c5.jpg)


![3b](https://user-images.githubusercontent.com/10054173/36289803-de9ad50c-1276-11e8-8371-a3c6a5d079b2.jpg)

**Comment by yazhai** [comment]
Yes, I will be at office the whole morning until 4PM.

I used to test VTune once, but it did not support OpenMP well as I expected.

**Comment by chemphys** [comment]
@dgasmith , seems like using a step of 1 in the [2b](https://github.com/chemphys/clusters_ultimate/blob/mrr/parallelization/src/bblock/system.cpp#L302) and [3b](https://github.com/chemphys/clusters_ultimate/blob/mrr/parallelization/src/bblock/system.cpp#L470) functions improves considerably the speedup. However, there is still this drop for 12 cores that I cannot fix. I will rerun with VTune and 12 cores to see if there is anything that I am not taking into account.

![2b](https://user-images.githubusercontent.com/10054173/36291086-cc71ade0-127d-11e8-9228-0bf85e6c2691.jpg)


![3b](https://user-images.githubusercontent.com/10054173/36291091-cf76ea96-127d-11e8-8c6e-5c86138b013c.jpg)

**Comment by dgasmith** [comment]
@chemphys If you are not using static OMP schedulers and pinning your threads it is often difficult to get good performance with OMP alone on nodes with NUMA. Effectively, a processor is going to need data that is associated with a different processor and moving the data between these NUMA domains is quite expensive.

**Comment by chemphys** [comment]
The problem is that static scheduling here won't work, since usually the first iterations of the loop are the most expensive ones, and then it starts decreasing. When I run VTune I saw that the master thread was always busy in the parallel regions, the forst worker thread was less busy, the second even less... and so on. That is why I decided to go with dynamic shcheduling.

I can try a reorganization and use static scheduling, but I don't think it will improve it so much. 
What do you recommend?

**Comment by dgasmith** [comment]
To do static you need to reorganize the blocks so that each has equal work. This is not always an easy task to accomplish, but will help with your NUMA issues. This would involve clustering the 2-body into equal work groups rather than simply running over the possibilities.

**Comment by chemphys** [comment]
I think I can do that, but will require a little bit of time. The work load difference between the different iterations of the loop is due to the fact that some dimers (since I am looking for a lot of them) are farther than what the polynomials accept, and thus are not evaluated. That makes that loop go considerably faster.

As a reminder, this is what the 2B and 3B loops do:
1. Get all dimers (trimers) <i,j> (<i,j,k>) for which i is in between the range **istart** and **iend** (**iend** not included), whichout mattering if the monomers are of the same type or not.  
2. Fill coordinates until you find a different type of dimer/trimer and send it to get the energy.
3. Once you are done looping over all the dimers (trimers), update istart and i end, and repeat the iteration.

For the 2B, the solution (i think) is slightly simpler. I can loop over monomer types instead of purely monomers. Then get the clusters that I know that I will compute with a personalized cutoff for that dimer type (I can create a function that recovers it). This might reduce the amount of time spent in clustering. For this I will have to treat dispersion and polynomials in two different functions.

For the three body I will have to modify the clustering, so it takes 3 sets of coordinates and I can control better the clusters I get, instead of getting whatever type as I get now.

Sounds reasonable? It will take me a while but I think it might improve the speedup.
Thanks!

**Comment by yazhai** [comment]
@chemphys will you be in SDSC some time today? Or perhaps next week?
I'm also doing some profiling with OpenMP, but my issue is most likely with regards of cache and memory, and work balance is the next thing.

**Comment by chemphys** [comment]
Hey @yazhai , sorry, but I will come next week. Today I got busy. 
We can see if we can make that work well.

**Comment by yazhai** [comment]
@chemphys sure, np. Have a good weekend.

**Comment by chemphys** [comment]
Hey @dgasmith ,

I run the timings on TSCC (16 cores, 2 sockets of 8), since I was not sure if when I was using 12 cores on my machine, I was actually using 12 (I am running several workspaces, with chrome, and so on). These are the speedups I get. Aparently, the dynamic schedule seems to work very well for large systems, but if #water molecules < 4 * ncores, the scaling drops fast.

Do you think is still necessary to reorganize the clustering with similar types? I have been thinking about it for a couple days, and it would require doing a few more loops with less coordinates, in ordr to retrieve all the different pairs and triplets.

In any case, I will parallelize the regions of the electrostatics that are not parallel yet, and then we can go back to this.

See you!

![2b](https://user-images.githubusercontent.com/10054173/36356433-e7f9d350-14a6-11e8-86bf-28cff9e873a3.jpg)

![3b](https://user-images.githubusercontent.com/10054173/36356434-eabf74b4-14a6-11e8-86b1-05e6f045dce2.jpg)

**Comment by dgasmith** [comment]
Ah, I didn't know you had other processes on your computer while timing. That may be responsible as the TSCC results look quite good and honestly more inline with what I was expecting from a pretty easy parallel region. 

For the static vs dynamic results: I agree that using static will take some time to figure out, it is always a tradeoff to go to something like static vs the niceties of dynamic. Rewriting for static is up to you and your use cases. If you anticipate running a lot of say 64 water clusters where 3B could be a bottleneck and you are worried about wall-hours rather than core-hours (often is the case with MD) it may be worth your time to look into it.

That being said: this no longer looks NUMA related and you may want to try something simpler. It would likely be worth your time to play around a bit with dynamic vs guided scheduling and using different chunk sizes. I believe there is "the best" answer, but learning a bit about different schedulers and getting a feel for how they work could be instructive.

**Comment by chemphys** [comment]
I agree. I just tried dynamic scheduling without specifying a chunk size. I can see what happens if I use guided scheduling, but for what I have read in different openmp tutorial websites, dynamic scheduling migh have same or better performance than guided. I will play witch dynamic, guided and different chunks and see what is the best thing to do for the different sizes.

**Comment by chemphys** [comment]
Hey @dgasmith ,
I finalized implementation of parallel regions in electrostatics. I parallelized the permanent electric field calculation, and the gradient calculation. To give you an idea, here are the times, in ms, of what it takes to obtain the energy for a system of N water molecules.
```
      N       t / ms
      16         72
      32        231
      64        849
     128       2914
     256       9532
     512      31986
    1024     109502
```
And this is how the speed up plots look like for the total energy and the electrostatics, using dynamic schedule.

![electrostatics](https://user-images.githubusercontent.com/10054173/36400389-712c93b8-1585-11e8-973b-2abc27cbf29b.jpg)

![totalenergy](https://user-images.githubusercontent.com/10054173/36400392-767a5968-1585-11e8-86c5-aa8275302319.jpg)

The guided and static schemes are usually way worst or similar than the dynamic schedule.The guided scheme always gets a chunk of size N/np at the beggining, bt since in our case the first iterations is always more expensive than the second one, the second one than the third one... and so on, this doesn't work. 
I will try to invert the loop and see what happens with the guided.

**Comment by dgasmith** [comment]
You can always change the chunk size from the start. But yea, inverting the loop may help the algorithm.

Overall, I think this looks good for a first pass. I suspect if we need to go faster we can probably get better gains in algorithm design over squeezing a few more percent out of the upper end.

We just need to note below 64/128 water molecules or so performance goes down quite steeply for large numbers of threads.

**Comment by chemphys** [comment]
Seems that for now this is set. We will come back if we want to improve the performance of N < 128 water molecules. Closing issue.
