### ISSUE TITLE
PBC dispersion

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#44]
Hey @dgasmith ,

I remember that when we talked about periodic boundary conditions, you mentioned that usually, to ensure integration, one sets the dispersion at the cutoff to 0, and shifts the whole potential.
We can talk about the best way to do this on Monday, if that is OK for you. Here is Spring Break, and I don't know if you guys have this too, but I will be at school for sure.

As an update for PBC, I have the 1B and 2B (poly + dispersion) working, but probably in not the most efficient way. I will implement the 3B, and then tackle the electrostatics.

**Comment by dgasmith** [comment]
Ah, we are here and I was unaware of any spring break so I was planning to meet regardless. Yes, with PBC we have a bit to talk about. Unfortunately I do not know of any good links to begin that conversation.

**Comment by chemphys** [comment]
@andysim , I opened this issue a while ago, but is also something to remember. As today's date, the dispersion in PBC is scaled. This means that for each pair, the dispersion is scaled so at the cutoff distance gets the value of 0. I recall you saying that there was a better way to do this. Just to keep it in mind.

**Comment by chemphys** [comment]
Issue solved. We added PME for dispersion.
Closing!
