### ISSUE TITLE
CMake Behaving weird for the plugin

### ISSUE THREAD

**Issue by chemphys** [paesanilab/clusters_ultimate#45]
Hey @dgasmith ,
Once I am done with a couple of minor things to polish, I would appreciate if we can sit together and figure out a way to make CMake work properly. I open this issue to remind me to do it.
For now, the following things are not behaving well:
- Need to find a way to decide which compiler to use (intel/clang/gnu)
- Seems like CMake is not accepting to use the std=c++11

In principle, fixing this should make things work properly.
No reply needed, but we will have to work on this. I already tried everything google told me, but there is some key information that I am missing (and I am sure is too trivial).
Thanks in advance!

**Comment by dgasmith** [comment]
The `--DCMAKE_CXX_COMPILER` flag switches the compiler when you run CMake. Without this flag, CMake chooses the first compiler in your path. For C++ standards the following is need:

```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
